# Generated by Django 2.2.16 on 2021-03-29 19:05

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '002_migration_for_hstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='options_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('fields_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('risk_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_type', to='main.RiskType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
